"""add weights

Revision ID: 21e2601ad137
Revises: 9a984f02a7ad
Create Date: 2025-11-06 15:20:07.775039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e2601ad137'
down_revision: Union[str, Sequence[str], None] = '9a984f02a7ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('classes', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weights')),
    sa.UniqueConstraint('name', name=op.f('uq_weights_name')),
    sa.UniqueConstraint('path', name=op.f('uq_weights_path'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weights')
    # ### end Alembic commands ###
